// <auto-generated />
using System;
using CarDealershipDemo.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarDealershipDemo.Infra.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260426170246_UseTimestampDefaultValue")]
    partial class UseTimestampDefaultValue
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarDealershipDemo.Core.Entities.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("color_nm");

                    b.Property<string>("ColorHexCode")
                        .IsRequired()
                        .HasColumnType("char(7)")
                        .HasColumnName("color_hex_cd");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_dt")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<string>("Drivetrain")
                        .IsRequired()
                        .HasColumnType("char(3)")
                        .HasColumnName("drivetrain_cd");

                    b.Property<bool>("HasHeatedSeats")
                        .HasColumnType("bit")
                        .HasColumnName("heated_seats_in");

                    b.Property<bool>("HasNavigation")
                        .HasColumnType("bit")
                        .HasColumnName("navigation_in");

                    b.Property<bool>("HasPowerWindows")
                        .HasColumnType("bit")
                        .HasColumnName("power_windows_in");

                    b.Property<bool>("HasSunroof")
                        .HasColumnType("bit")
                        .HasColumnName("sunroof_in");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasColumnName("active_in")
                        .HasDefaultValueSql("1");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("mfr_nm");

                    b.Property<int>("Miles")
                        .HasColumnType("int")
                        .HasColumnName("mileage_qty");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_dt")
                        .HasDefaultValueSql("current_timestamp");

                    b.Property<decimal>("Price")
                        .HasColumnType("money")
                        .HasColumnName("price_amt");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("model_yr");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"), false);

                    b.HasIndex("CreatedDate", "Id");

                    SqlServerIndexBuilderExtensions.IsClustered(b.HasIndex("CreatedDate", "Id"));

                    b.ToTable("car", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
